language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux

sudo: false

install:
  - "pip install -U pip"
  - "pip install -U setuptools"
  - "pip install gevent-websocket pyopenssl"
  - "pip install coverage pytest-cov coveralls"
  - python setup.py install

script:
  - python setup.py test

after_success:
  - coveralls

