language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux

sudo: false

install:
  - python setup.py install
  - pip install -U pip
  - pip install gevent-websocket coverage pytest-cov coveralls

script:
  - python setup.py test

after_success:
  - coveralls

